[2025-04-22T21:25:51.287+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-22T21:25:51.295+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-04-22T21:25:49.768672+00:00 [queued]>
[2025-04-22T21:25:51.297+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2025-04-22T21:25:49.768672+00:00 [queued]>
[2025-04-22T21:25:51.298+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-22T21:25:51.305+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run> on 2025-04-22 21:25:49.768672+00:00
[2025-04-22T21:25:51.318+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1346) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-22T21:25:51.313+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2025-04-22T21:25:49.768672+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpf7u7sp4f']
[2025-04-22T21:25:51.321+0000] {standard_task_runner.py:105} INFO - Job 169: Subtask dbt_run
[2025-04-22T21:25:51.320+0000] {standard_task_runner.py:72} INFO - Started process 1347 to run task
[2025-04-22T21:25:51.340+0000] {task_command.py:467} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2025-04-22T21:25:49.768672+00:00 [running]> on host 94fb330c57fd
[2025-04-22T21:25:51.404+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T21:25:49.768672+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-22T21:25:49.768672+00:00'
[2025-04-22T21:25:51.404+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-22T21:25:51.411+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-22T21:25:51.411+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-04-22T21:25:51.415+0000] {subprocess.py:86} INFO - Output:
[2025-04-22T21:25:52.735+0000] {subprocess.py:93} INFO - [0m21:25:52  Running with dbt=1.7.5
[2025-04-22T21:25:53.160+0000] {subprocess.py:93} INFO - [0m21:25:53  Registered adapter: snowflake=1.7.5
[2025-04-22T21:25:53.163+0000] {subprocess.py:93} INFO - [0m21:25:53  Unable to do partial parsing because saved manifest not found. Starting full parse.
[2025-04-22T21:25:53.629+0000] {subprocess.py:93} INFO - [0m21:25:53  Found 3 models, 1 snapshot, 3 sources, 0 exposures, 0 metrics, 431 macros, 0 groups, 0 semantic models
[2025-04-22T21:25:53.630+0000] {subprocess.py:93} INFO - [0m21:25:53
[2025-04-22T21:25:54.599+0000] {subprocess.py:93} INFO - [0m21:25:54
[2025-04-22T21:25:54.601+0000] {subprocess.py:93} INFO - [0m21:25:54  Finished running  in 0 hours 0 minutes and 0.97 seconds (0.97s).
[2025-04-22T21:25:54.602+0000] {subprocess.py:93} INFO - [0m21:25:54  Encountered an error:
[2025-04-22T21:25:54.603+0000] {subprocess.py:93} INFO - Database Error
[2025-04-22T21:25:54.603+0000] {subprocess.py:93} INFO -   003001 (42501): SQL access control error:
[2025-04-22T21:25:54.604+0000] {subprocess.py:93} INFO -   Insufficient privileges to operate on database 'USER_DB_LEMMING'
[2025-04-22T21:25:55.275+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-04-22T21:25:55.281+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-22T21:25:55.282+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2025-04-22T21:25:49.768672+00:00, execution_date=20250422T212549, start_date=20250422T212551, end_date=20250422T212555
[2025-04-22T21:25:55.287+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-22T21:25:55.287+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 169 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 1347)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-04-22T21:25:55.308+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-22T21:25:55.316+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-22T21:25:55.317+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
